author: 张大发
description: sugar's blog, 记录生活点点滴滴
domain: sugar.050701.live

excerpt_separator: "<separator/>"
timezone: Asia/Shanghai
paginate: 5
site.baseurl: /sugar
paginate_path: "page:num"

gems: [jekyll-paginate]